pipelines:
  - name: hello_world_art
    steps:
      - name: first_art
        type: Bash
        configuration:
          integrations:
            - name: int_artifactory
        execution:
          onStart:
            - echo "onStart can be used to do some setup or initialization of your dependencies to prepare for the execution."
          onExecute:
            - echo "onExecute is the main section where you would issue your build/test commands"
            - jfrog --version
